import json
import aws_cdk as cdk
from aws_cdk import (
    Stack,
    CfnOutput,
    aws_ec2 as ec2,
    aws_iam as iam,
    aws_secretsmanager as sm,
)
from constructs import Construct

REPO_URL = "https://github.com/Dreadonyx/Certs-Automator.git"

# User-data script that runs at first boot (as root).
# It installs Docker and docker-compose, then clones the repo and
# delegates the rest to scripts/server-setup.sh inside the repo.
BOOTSTRAP = f"""#!/bin/bash
set -euo pipefail
exec > >(tee /var/log/certflow-init.log) 2>&1

echo "=== Installing Docker and git ==="
dnf update -y
dnf install -y docker git
systemctl enable --now docker
usermod -aG docker ec2-user

echo "=== Installing Docker Compose v2 plugin ==="
ARCH=$(uname -m)
mkdir -p /usr/local/lib/docker/cli-plugins
curl -fsSL \
  "https://github.com/docker/compose/releases/latest/download/docker-compose-linux-${{ARCH}}" \
  -o /usr/local/lib/docker/cli-plugins/docker-compose
chmod +x /usr/local/lib/docker/cli-plugins/docker-compose

echo "=== Installing Docker Buildx plugin ==="
mkdir -p /home/ec2-user/.docker/cli-plugins
curl -fsSL \
  "https://github.com/docker/buildx/releases/latest/download/buildx-linux-amd64" \
  -o /home/ec2-user/.docker/cli-plugins/docker-buildx
chmod +x /home/ec2-user/.docker/cli-plugins/docker-buildx
chown -R ec2-user:ec2-user /home/ec2-user/.docker

echo "=== Cloning CertFlow repository ==="
cd /home/ec2-user
git clone {REPO_URL} Certs-Automator
chown -R ec2-user:ec2-user Certs-Automator

echo "=== Running app setup as ec2-user ==="
su - ec2-user -c "bash /home/ec2-user/Certs-Automator/scripts/server-setup.sh"

echo "=== Bootstrap complete ==="
"""


class CertflowStack(Stack):
    def __init__(self, scope: Construct, id: str, **kwargs) -> None:
        super().__init__(scope, id, **kwargs)

        # ── Default VPC ────────────────────────────────────────────────────
        vpc = ec2.Vpc.from_lookup(self, "DefaultVpc", is_default=True)

        # ── Security group ─────────────────────────────────────────────────
        sg = ec2.SecurityGroup(
            self,
            "CertflowSG",
            vpc=vpc,
            description="CertFlow - HTTP, HTTPS, SSH",
            allow_all_outbound=True,
        )
        sg.add_ingress_rule(ec2.Peer.any_ipv4(), ec2.Port.tcp(22),  "SSH")
        sg.add_ingress_rule(ec2.Peer.any_ipv4(), ec2.Port.tcp(80),  "HTTP")
        sg.add_ingress_rule(ec2.Peer.any_ipv4(), ec2.Port.tcp(443), "HTTPS")

        # ── Secrets Manager ────────────────────────────────────────────────
        # SECRET_KEY is auto-generated by Secrets Manager.
        # After deploy, update ADMIN_PASSWORD_HASH, DOMAIN_NAME, DUCKDNS_TOKEN
        # via: bash scripts/update-secrets.sh  (see that script for instructions)
        secret = sm.Secret(
            self,
            "CertflowAppSecrets",
            secret_name="certflow/app-secrets",
            description="CertFlow runtime secrets - update ADMIN_PASSWORD_HASH and DUCKDNS_TOKEN after deploy",
            generate_secret_string=sm.SecretStringGenerator(
                secret_string_template=json.dumps({
                    "ADMIN_USERNAME": "admin",
                    "ADMIN_PASSWORD_HASH": "REPLACE_WITH_ARGON2ID_HASH",
                    "DOMAIN_NAME": "certflow.duckdns.org",
                    "DUCKDNS_TOKEN": "REPLACE_WITH_DUCKDNS_TOKEN",
                    "RATELIMIT_STORAGE_URI": "redis://redis:6379",
                    "SESSION_COOKIE_SECURE": "true",
                    "SESSION_COOKIE_SAMESITE": "Strict",
                    "SESSION_LIFETIME_SECONDS": "28800",
                    "GLOBAL_RATE_LIMIT": "200 per hour",
                    "LOGIN_RATE_LIMIT": "5 per minute",
                    "MAX_REQUEST_BYTES": "33554432",
                    "MAX_IMAGE_BYTES": "10485760",
                    "MAX_IMAGE_PIXELS": "25000000",
                    "MAX_CSV_ROWS": "2000",
                    "MAX_PARTICIPANTS": "2000",
                    "MAX_ZIP_ENTRIES": "500",
                    "MAX_NAME_LENGTH": "200",
                }),
                generate_string_key="SECRET_KEY",
                exclude_punctuation=True,
                password_length=64,
            ),
        )

        # ── IAM role ───────────────────────────────────────────────────────
        role = iam.Role(
            self,
            "CertflowInstanceRole",
            assumed_by=iam.ServicePrincipal("ec2.amazonaws.com"),
            managed_policies=[
                iam.ManagedPolicy.from_aws_managed_policy_name(
                    "AmazonSSMManagedInstanceCore"
                )
            ],
        )
        secret.grant_read(role)

        # ── SSH key pair (reuse existing 'certflow-key' already in the account)
        key_pair = ec2.KeyPair.from_key_pair_name(
            self,
            "CertflowKeyPair",
            "certflow-key",
        )

        # ── EC2 instance ───────────────────────────────────────────────────
        instance = ec2.Instance(
            self,
            "CertflowInstance",
            vpc=vpc,
            instance_type=ec2.InstanceType.of(
                ec2.InstanceClass.T3, ec2.InstanceSize.SMALL
            ),
            machine_image=ec2.MachineImage.latest_amazon_linux2023(),
            security_group=sg,
            role=role,
            key_pair=key_pair,
            user_data=ec2.UserData.custom(BOOTSTRAP),
            block_devices=[
                ec2.BlockDevice(
                    device_name="/dev/xvda",
                    volume=ec2.BlockDeviceVolume.ebs(
                        20,
                        volume_type=ec2.EbsDeviceVolumeType.GP3,
                        encrypted=True,
                    ),
                )
            ],
        )

        # ── Elastic IP ─────────────────────────────────────────────────────
        eip = ec2.CfnEIP(
            self,
            "CertflowEIP",
            instance_id=instance.instance_id,
            tags=[cdk.CfnTag(key="Name", value="certflow-eip")],
        )

        # ── Outputs ────────────────────────────────────────────────────────
        CfnOutput(self, "InstanceId",
            value=instance.instance_id,
            description="EC2 instance ID",
        )
        CfnOutput(self, "ElasticIP",
            value=eip.attr_public_ip,
            description="Public IP - point your domain here",
        )
        CfnOutput(self, "SecretArn",
            value=secret.secret_arn,
            description="Secrets Manager ARN - update ADMIN_PASSWORD_HASH and DUCKDNS_TOKEN here",
        )
        CfnOutput(self, "KeyPairName",
            value="certflow-key",
            description="Existing key pair used - you already have certflow-key.pem",
        )
        CfnOutput(self, "SSHCommand",
            value=cdk.Fn.join("", [
                "ssh -i certflow-key.pem ec2-user@", eip.attr_public_ip
            ]),
            description="SSH command once key is downloaded",
        )
